[project]
name = 'Existence-Forking-and-Merging-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-reality-integration]
path = 'contracts/cross-reality-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.existence-branch-management]
path = 'contracts/existence-branch-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-snapshot]
path = 'contracts/reality-snapshot.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
